# /etc/bashrc

# System wide functions and aliases
# Environment stuff goes in /etc/profile

# It's NOT a good idea to change this file unless you know what you
# are doing. It's much better to create a custom.sh shell script in
# /etc/profile.d/ to make custom changes to your environment, as this
# will prevent the need for merging in future updates.

# are we an interactive shell?
if [ "$PS1" ]; then
  if [ -z "$PROMPT_COMMAND" ]; then
    case $TERM in
    xterm*)
        if [ -e /etc/sysconfig/bash-prompt-xterm ]; then
            PROMPT_COMMAND=/etc/sysconfig/bash-prompt-xterm
        else
            PROMPT_COMMAND='printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/~}"'
        fi
        ;;
    screen)
        if [ -e /etc/sysconfig/bash-prompt-screen ]; then
            PROMPT_COMMAND=/etc/sysconfig/bash-prompt-screen
        else
            PROMPT_COMMAND='printf "\033]0;%s@%s:%s\033\\" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/~}"'
        fi
        ;;
    *)
        [ -e /etc/sysconfig/bash-prompt-default ] && PROMPT_COMMAND=/etc/sysconfig/bash-prompt-default
        ;;
      esac
  fi
  # Turn on checkwinsize
  shopt -s checkwinsize
  [ "$PS1" = "\\s-\\v\\\$ " ] && PS1="[\u@\h \W]\\$ "
  # You might want to have e.g. tty in prompt (e.g. more virtual machines)
  # and console windows
  # If you want to do so, just add e.g.
  # if [ "$PS1" ]; then
  #   PS1="[\u@\h:\l \W]\\$ "
  # fi
  # to your custom modification shell script in /etc/profile.d/ directory
fi

if ! shopt -q login_shell ; then # We're not a login shell
    # Need to redefine pathmunge, it get's undefined at the end of /etc/profile
    pathmunge () {
        case ":${PATH}:" in
            *:"$1":*)
                ;;
            *)
                if [ "$2" = "after" ] ; then
                    PATH=$PATH:$1
                else
                    PATH=$1:$PATH
                fi
        esac
    }

    # By default, we want umask to get set. This sets it for non-login shell.
    # Current threshold for system reserved uid/gids is 200
    # You could check uidgid reservation validity in
    # /usr/share/doc/setup-*/uidgid file
    if [ $UID -gt 199 ] && [ "`id -gn`" = "`id -un`" ]; then
       umask 002
    else
       umask 022
    fi

    # Only display echos from profile.d scripts if we are no login shell
    # and interactive - otherwise just process them to set envvars
    for i in /etc/profile.d/*.sh; do
        if [ -r "$i" ]; then
            if [ "$PS1" ]; then
                . "$i"
            else
                . "$i" >/dev/null 2>&1
            fi
        fi
    done

    unset i
    unset pathmunge
fi
# vim:ts=4:sw=4
alias python='/usr/bin/python2.6'
unset SSH_ASKPASS
git config --global http.sslVerify false

export TMOUT=36000
export HISTFILESIZE=1000
export HISTSIZE=1000
export TZ='America/New_York'
#echo never>/sys/kernel/mm/transparent_hugepage/defrag
#echo never>/sys/kernel/mm/transparent_hugepage/enabled
export JAVA_HOME=/usr/java/jdk1.8.0_131
export JRE_HOME=/usr/java/jdk1.8.0_131/jre
#export JAVA_HOME=/opt/jdk1.7.0_80
export JAVA_TOOL_OPTIONS="-Xss2m"
export HADOOP_HOME=/opt/cloudera/parcels/CDH/lib/hadoop
export HADOOP_PREFIX=/opt/cloudera/parcels/CDH/lib/hadoop
export HIVE_HOME=/opt/cloudera/parcels/CDH/lib/hive
export SQOOP_HOME=/opt/cloudera/parcels/CDH/lib/sqoop
export HBASE_HOME=/opt/cloudera/parcels/CDH/lib/hbase
export ACCUMULO_HOME=/var/lib/accumulo
export HADOOP_CLASSPATH=$SQOOP_HOME/lib/jconn4.jar:$SQOOP_HOME/lib/bcprov-jdk16-1.46.jar:$HIVE_HOME/lib/*:$HBASE_HOME/lib/*:$HBASE_HOME/conf
export SQOOP_CLASSPAT=$SQOOP_HOME/lib/jconn4.jar:$SQOOP_HOME/lib/bcprov-jdk16-1.46.jar
export M2_HOME=/usr/book/opt/apache-maven-3.5.3
export PATH=/usr/local/git/bin:$PATH:/usr/java/jdk1.8.0_131/bin:$M2_HOME/bin:$HADOOP_HOME/bin
export CLASSPATH=$CLASSPATH:$HADOOP_HOME/lib/*:$HIVE_HOME/lib/*:$HBASE_HOME/lib/*:$HBASE_HOME/*:.
export REPOSITORY=/usr/book/repository/com/yieldbook
export CLASSPATH=$CLASSPATH:$REPOSITORY/embs/resources:$REPOSITORY/HBaseJava/resources
